"""Geo + content data for the Bender Realty site generator."""

# Each community: slug, name, blurb (unique intro copy), extra (optional 2nd paragraph angle)
COUNTIES = [
    {
        "slug": "bradley-county",
        "name": "Bradley County",
        "seat": "Cleveland",
        "kicker": "Cleveland · Charleston · McDonald",
        "img": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=1400&q=70",
        "blurb": "Bradley County is the heart of Bender Realty's service area and home to our Cleveland office. Anchored by Cleveland — one of Tennessee's fastest-growing small cities — the county blends established in-town neighborhoods, newer subdivisions, rural acreage, and easy access to I-75, Chattanooga, and the Ocoee region.",
        "extra": "Buyers are drawn to Bradley County for its strong schools, Lee University, a healthy job base, and home prices that remain reasonable compared to the Chattanooga metro. Whether you want a historic home near downtown Cleveland, new construction near Hopewell, or land toward Charleston, our agents know every corner of this county.",
        "communities": [
            ("cleveland", "Cleveland", "Cleveland is the county seat of Bradley County and the hub of Southeast Tennessee living — a growing city of roughly 50,000 known for Lee University, a revitalized downtown, strong schools, and quick access to both Chattanooga and the mountains. Homes range from historic districts near downtown to newer subdivisions on the north and south ends of town."),
            ("north-cleveland", "North Cleveland", "North Cleveland covers the neighborhoods north of downtown toward Charleston and I-75 exit 27 — an area popular for newer subdivisions, convenient shopping along Paul Huff Parkway, and some of the county's most requested school zones."),
            ("south-cleveland", "South Cleveland", "South Cleveland stretches from downtown toward the Hamilton County line, offering established neighborhoods, larger lots, and quick access to APD-40 and Highway 64 toward Chattanooga and Ocoee."),
            ("charleston", "Charleston", "Charleston sits on the Hiwassee River at Bradley County's northern edge, a small historic town with riverside character, rural land, and a location minutes from I-75 — a favorite for buyers who want space without giving up convenience."),
            ("hopewell", "Hopewell", "Hopewell is a fast-growing community in northern Bradley County where newer subdivisions meet farmland. It offers newer-built homes, acreage tracts, and a country feel just minutes from Cleveland's shopping and schools."),
            ("mcdonald", "McDonald", "McDonald sits along the Bradley–Hamilton county line, putting Chattanooga, Ooltewah, and Cleveland all within an easy drive. The area is known for larger lots, mini-farms, and newer homes with a rural backdrop."),
            ("black-fox-wildwood-lake", "Black Fox & Wildwood Lake", "Black Fox and Wildwood Lake are established neighborhood areas on Cleveland's south side, offering mature trees, a mix of mid-century and newer homes, and quick access to APD-40 and South Lee Highway."),
        ],
    },
    {
        "slug": "polk-county",
        "name": "Polk County",
        "seat": "Benton",
        "kicker": "Benton · Ocoee · Copperhill",
        "img": "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=1400&q=70",
        "blurb": "Polk County is Southeast Tennessee's outdoor playground — home to the Ocoee River, the Cherokee National Forest, and the mountain towns of the Copper Basin. Real estate here means riverfront cabins, mountain acreage, hunting land, and small-town homes in Benton, Ocoee, Copperhill, and Ducktown.",
        "extra": "Because so much of Polk County is national forest, private land is limited — which makes local knowledge essential when buying or selling here. Bender Realty helps clients navigate mountain properties, unrestricted acreage, and recreational land throughout the county.",
        "communities": [
            ("benton", "Benton", "Benton is the county seat of Polk County, a small town at the foot of the Chilhowee Mountains along Highway 411. Buyers find affordable homes, farms, and acreage here, with the Hiwassee River and Cherokee National Forest minutes away."),
            ("ocoee", "Ocoee", "Ocoee is the gateway to the Ocoee River — world-famous whitewater and the 1996 Olympic venue. The area offers cabins, riverside retreats, and wooded acreage popular with outdoor enthusiasts and short-term-rental investors."),
            ("copperhill", "Copperhill", "Copperhill sits on the Tennessee–Georgia line in the historic Copper Basin, sharing a walkable downtown with McCaysville, GA. Its mining heritage, mountain views, and small-town storefronts attract full-time residents and second-home buyers alike."),
            ("ducktown", "Ducktown", "Ducktown is a historic Copper Basin mining town surrounded by the Cherokee National Forest. Buyers come for affordable mountain homes, cabins, and land within a short drive of the Ocoee River and Blue Ridge, GA."),
            ("conasauga", "Conasauga", "Conasauga is a quiet rural community in southern Polk County near the Georgia line, where properties tend toward farmland, timbered acreage, and country homes well off the beaten path."),
            ("delano", "Delano", "Delano lies along the Hiwassee River corridor in northern Polk County, known for riverfront land, farms, and easy access to Highway 411 between Benton and Etowah."),
            ("farner", "Farner", "Farner is one of Tennessee's most remote communities, tucked into the mountains of upper Polk County near the North Carolina line — a place for cabins, creekside land, and true seclusion."),
            ("reliance-cherokee-national-forest", "Reliance & Cherokee National Forest", "Reliance is a historic river community on the Hiwassee, surrounded by the Cherokee National Forest. Properties near Reliance offer trout-stream frontage, mountain views, and a legendary slice of Tennessee river country."),
        ],
    },
    {
        "slug": "mcminn-county",
        "name": "McMinn County",
        "seat": "Athens",
        "kicker": "Athens · Etowah · Niota",
        "img": "https://images.unsplash.com/photo-1449844908441-8829872d2607?w=1400&q=70",
        "blurb": "McMinn County sits between Chattanooga and Knoxville along the I-75 corridor, anchored by the college town of Athens and the railroad town of Etowah. The county offers classic small-town neighborhoods, working farms, and commuter-friendly locations with genuine Tennessee character.",
        "extra": "With Tennessee Wesleyan University, a diversified industrial base, and a courthouse-square downtown, Athens gives McMinn County a stability that buyers appreciate. Bender Realty serves the entire county, from in-town homes to farmland in Riceville and Calhoun.",
        "communities": [
            ("athens", "Athens", "Athens is the seat of McMinn County and home to Tennessee Wesleyan University — a classic courthouse-square town halfway between Chattanooga and Knoxville on I-75. Buyers find historic homes near downtown, newer subdivisions, and farms just outside the city."),
            ("etowah", "Etowah", "Etowah grew up around the L&N Railroad, and its historic depot still anchors the town. Affordable homes, a walkable old-town grid, and proximity to the Cherokee National Forest and Hiwassee River make Etowah a small-town value."),
            ("niota", "Niota", "Niota is a small McMinn County town along the I-75 corridor with Tennessee's oldest operating railroad depot. The surrounding countryside offers farms, acreage, and quiet rural homesites within commuting distance of Athens and Sweetwater."),
            ("englewood", "Englewood", "Englewood is a former textile-mill town at the edge of the Unicoi Mountains, offering affordable homes and easy access to Highway 411, the Cherokee National Forest, and the Tellico area."),
            ("claxton", "Claxton", "Claxton is a rural community in southern McMinn County between Athens and Calhoun, where buyers look for farmland, acreage, and country homes convenient to both I-75 and Highway 11."),
            ("calhoun-riceville", "Calhoun & Riceville", "Calhoun and Riceville sit along the Hiwassee River corridor between Athens and Charleston. The area mixes riverside land, farms, and affordable homes with quick access to I-75 and the industrial employers along Highway 11."),
        ],
    },
    {
        "slug": "meigs-county",
        "name": "Meigs County",
        "seat": "Decatur",
        "kicker": "Decatur · Ten Mile · Watts Bar",
        "img": "https://images.unsplash.com/photo-1476673160081-cf065607f449?w=1400&q=70",
        "blurb": "Meigs County is one of Southeast Tennessee's best-kept secrets — a quiet, rural county bordered by Chickamauga Lake and Watts Bar Lake on the Tennessee River. Lakefront property, farmland, and small-town homes in Decatur define the market here, often at prices well below neighboring counties.",
        "extra": "With two major lakes, no interstate congestion, and a location within an hour of Chattanooga and Knoxville, Meigs County attracts lake buyers, retirees, and anyone looking for land with water access. Bender Realty covers the county from Decatur to Ten Mile.",
        "communities": [
            ("decatur", "Decatur", "Decatur is the county seat of Meigs County, a small town surrounded by farmland between Chickamauga and Watts Bar lakes. Buyers find affordable homes, acreage, and a genuine rural pace within easy reach of Athens, Cleveland, and Dayton."),
            ("ten-mile", "Ten Mile", "Ten Mile sits at the northern end of Meigs County on Watts Bar Lake, a favorite for lakefront homes, boat-dock properties, and weekend retreats — with some of the most affordable big-water frontage in East Tennessee."),
            ("big-spring", "Big Spring", "Big Spring is a rural Meigs County community between Decatur and Birchwood, known for rolling farmland, long-range views, and larger tracts of land near the Chickamauga Lake side of the county."),
            ("birchwood", "Birchwood", "Birchwood straddles the Meigs–Hamilton county line near the Tennessee River, famous for its sandhill crane refuge. The area offers riverside land, mini-farms, and country homes about 30 minutes from Chattanooga."),
            ("georgetown", "Georgetown", "Georgetown sits where Meigs, Bradley, and Hamilton counties meet, giving residents an easy drive to Cleveland, Ooltewah, and Chattanooga. Buyers come here for newer homes on acreage and land near Chickamauga Lake."),
            ("euchee-watts-bar-lake", "Euchee & Watts Bar Lake", "The Euchee area fronts Watts Bar Lake in northern Meigs County, near the Euchee boat ramp and marina. It's a prime spot for lakefront living, fishing retreats, and dockable waterfront lots."),
        ],
    },
    {
        "slug": "hamilton-county",
        "name": "Hamilton County",
        "seat": "Chattanooga",
        "kicker": "Chattanooga · Ooltewah · Signal Mountain",
        "img": "https://images.unsplash.com/photo-1444723121867-7a241cacace9?w=1400&q=70",
        "blurb": "Hamilton County is the greater Chattanooga market — from riverside city neighborhoods to mountaintop communities and the fast-growing Ooltewah–Collegedale corridor next door to Bradley County. Bender Realty helps clients on the northeastern side of the metro, where our Cleveland base gives us a natural edge.",
        "extra": "Chattanooga's job growth, outdoor lifestyle, and national attention keep demand high across Hamilton County. From Ooltewah and Apison to Soddy-Daisy and Signal Mountain, our agents help buyers and sellers navigate one of Tennessee's most dynamic markets.",
        "communities": [
            ("chattanooga", "Chattanooga", "Chattanooga is Tennessee's scenic city — a revitalized riverfront downtown, thriving neighborhoods like North Shore and Southside, and an outdoor lifestyle few cities can match. Bender Realty helps buyers and sellers across the Chattanooga market, especially its northeastern corridors toward Cleveland."),
            ("ooltewah", "Ooltewah", "Ooltewah is one of the Chattanooga metro's fastest-growing communities, halfway between Chattanooga and Cleveland along I-75. Master-planned neighborhoods, top-rated schools, and Cambridge Square's shops and restaurants drive steady demand."),
            ("apison", "Apison", "Apison is a countryside community southeast of Ooltewah near the Georgia line, where new subdivisions meet horse farms and rolling pasture. Buyers love the East Hamilton school zone and the quick drive to both Chattanooga and Cleveland."),
            ("collegedale", "Collegedale", "Collegedale is home to Southern Adventist University and a family-friendly mix of established neighborhoods, new construction, and the popular greenway system connecting to Ooltewah."),
            ("harrison", "Harrison", "Harrison sits on the eastern shore of Chickamauga Lake, offering lakefront homes, Harrison Bay State Park, and an easy commute to Chattanooga, Ooltewah, or Cleveland."),
            ("east-ridge", "East Ridge", "East Ridge borders Chattanooga along the Georgia line, offering some of the metro's most affordable single-family homes, a central location off I-75, and ongoing reinvestment along Ringgold Road."),
            ("red-bank", "Red Bank", "Red Bank is a close-in Chattanooga suburb just north of downtown, popular with first-time buyers and renovators for its mid-century housing stock, small-business corridor on Dayton Boulevard, and five-minute drive to the North Shore."),
            ("soddy-daisy", "Soddy-Daisy", "Soddy-Daisy stretches along Chickamauga Lake north of Chattanooga, with lakefront and lake-access homes, mountain backdrops, and a small-town feel inside the Hamilton County school system."),
            ("signal-mountain", "Signal Mountain", "Signal Mountain rises above Chattanooga with brow-view homes, top-ranked schools, and a historic town center. Buyers come for the mountain lifestyle and stay for the community."),
            ("lookout-mountain", "Lookout Mountain", "Lookout Mountain is one of Chattanooga's most storied addresses — historic estates, brow lots overlooking the valley, and the landmarks of Rock City and Point Park."),
            ("walden", "Walden", "Walden occupies the quieter, wooded top of Signal Mountain, where larger lots, brow views, and the town's small commercial core create a private mountain community minutes from Chattanooga."),
            ("st-elmo", "St. Elmo", "St. Elmo is Chattanooga's historic neighborhood at the foot of Lookout Mountain, prized for Victorian homes, the Incline Railway, and walkability to trails and local restaurants."),
            ("sale-creek", "Sale Creek", "Sale Creek is a rural lakeside community at Hamilton County's northern tip, where Chickamauga Lake waterfront, farms, and acreage meet an easy Highway 27 commute to Chattanooga."),
            ("lakesite", "Lakesite", "Lakesite is a small lakeside city near Chester Frost Park on Chickamauga Lake, offering established neighborhoods, marina access, and a quick drive to Hixson's shopping."),
            ("middle-valley", "Middle Valley", "Middle Valley is a popular Hixson-area community between Big Ridge and Chickamauga Lake, with established subdivisions, parks, and convenient access to Highway 153."),
            ("falling-water", "Falling Water", "Falling Water sits at the base of Signal Mountain near its namesake waterfall, a small community offering mountain scenery and quick access to both Hixson and the mountaintop."),
            ("flat-top-mountain", "Flat Top Mountain", "Flat Top Mountain rises north of Soddy-Daisy with long-range views, gated acreage properties, and mountain homes that feel remote yet remain within 40 minutes of Chattanooga."),
            ("mowbray-mountain", "Mowbray Mountain", "Mowbray Mountain is a quiet plateau community above Soddy-Daisy, where buyers find acreage, privacy, and mountain-top living at approachable prices."),
            ("lupton-city", "Lupton City", "Lupton City is a historic mill village on the Tennessee River inside Chattanooga, now seeing new riverfront development alongside its original neighborhood streets."),
            ("fairmont", "Fairmont", "Fairmont is a mountain community on the way up Signal Mountain, offering wooded lots and homes with easy access to both the mountain's schools and the valley below."),
        ],
    },
]

# Property-type pages under /homes-for-sale/
HOME_TYPES = [
    ("lakefront", "Lakefront Homes", "Lakefront Homes for Sale in Southeast Tennessee",
     "Chickamauga Lake and Watts Bar Lake give Southeast Tennessee two of the state's best big-water lakes — and Bender Realty helps buyers find dockable lakefront homes, lake-access cottages, and waterfront lots on both. From Harrison and Soddy-Daisy on Chickamauga to Ten Mile and Euchee on Watts Bar, we know the coves, the dock permits, and the flood maps.",
     "Lakefront property comes with details that matter: TVA shoreline rights, dock permitting, water depth at the bank, and flood insurance. Our agents walk you through each one before you offer."),
    ("acreage", "Homes with Acreage", "Homes with Acreage for Sale in Southeast Tennessee",
     "Room to breathe is one of Southeast Tennessee's greatest luxuries. Bender Realty lists and sells homes on acreage across Bradley, Polk, McMinn, and Meigs counties — mini-farms, wooded tracts, pasture with barns, and country estates.",
     "When buying acreage, zoning, soil types, fencing, water sources, and easements all affect value. We help you evaluate land the way locals do."),
    ("new-construction", "New Construction", "New Construction Homes for Sale in Cleveland TN & Southeast Tennessee",
     "New neighborhoods are rising across Cleveland, Ooltewah, Hopewell, and Georgetown. Bender Realty helps buyers compare builders, floor plans, and communities — and negotiates on your behalf, because the builder's agent represents the builder, not you.",
     "From pre-construction contracts to final walk-throughs, our agents make sure new-build buyers understand allowances, upgrade pricing, and completion timelines."),
    ("luxury", "Luxury Homes", "Luxury Homes for Sale in Cleveland TN & Southeast Tennessee",
     "Southeast Tennessee's luxury market spans brow-view estates on Signal and Lookout Mountain, lakefront showplaces on Chickamauga, and acreage estates around Cleveland and Ooltewah. Bender Realty provides discreet, well-connected representation for buyers and sellers at the top of the market.",
     "Luxury transactions demand privacy, careful pricing, and marketing that reaches the right audience. Our team handles all three."),
    ("condos-townhomes", "Condos & Townhomes", "Condos & Townhomes for Sale in Cleveland TN & Chattanooga",
     "Low-maintenance living is growing across the region — townhome communities in Cleveland and Ooltewah, and condos in downtown Chattanooga. Bender Realty helps buyers weigh HOA terms, fees, and resale strength before they commit.",
     "HOA documents, rental restrictions, and reserve funding can make or break a condo purchase. We review them with you line by line."),
    ("golf-communities", "Golf Communities", "Golf Community Homes for Sale in Southeast Tennessee",
     "From the Cleveland Country Club area to golf-course neighborhoods around Chattanooga and Ooltewah, Bender Realty helps buyers find homes on and around the region's fairways.",
     "Golf-community buyers weigh course frontage, membership structures, and HOA covenants — details our agents track across every course community in the area."),
    ("single-story", "Single-Story Homes", "Single-Story & Ranch Homes for Sale in Cleveland TN",
     "One-level living is the region's most requested home style — for retirees, first-time buyers, and everyone who's done with stairs. Bender Realty tracks ranch and single-story inventory across Cleveland, Athens, and the surrounding counties.",
     "True one-level living means checking more than the bedroom count: laundry location, garage steps, and lot grading all matter. We know what to look for."),
    ("farm-ranch", "Farm & Ranch", "Farms & Ranch Properties for Sale in Southeast Tennessee",
     "Working farms, hobby farms, cattle land, and equestrian properties are a Bender Realty specialty across Bradley, McMinn, Meigs, and Polk counties — a region where agriculture is still a way of life.",
     "Farm transactions involve greenbelt tax status, water rights, outbuildings, and soil productivity. Our agents speak the language."),
    ("single-family", "Single-Family Homes", "Single-Family Homes for Sale in Cleveland TN & Southeast Tennessee",
     "The single-family home is the backbone of the Southeast Tennessee market — from starter homes in East Ridge and Athens to family neighborhoods across Cleveland and Ooltewah. Bender Realty helps buyers and sellers at every price point.",
     "Whatever your budget, our agents help you compare neighborhoods, school zones, and resale strength before you decide."),
    ("multi-family", "Multi-Family & Investment", "Multi-Family & Investment Properties for Sale in Cleveland TN",
     "Duplexes, fourplexes, and small apartment properties around Cleveland, Athens, and Chattanooga attract steady investor demand — and with ~500 units under management, Bender Realty brings real operating knowledge to every investment purchase.",
     "We help investors run the numbers on rents, vacancy, and maintenance — and our property management team can operate the asset after closing."),
    ("cabins-mountain-homes", "Cabins & Mountain Homes", "Cabins & Mountain Homes for Sale near the Ocoee & Cherokee National Forest",
     "The mountains of Polk County and the Cherokee National Forest are cabin country — weekend retreats near the Ocoee River, creekside hideaways around Reliance and Farner, and mountain homes in the Copper Basin.",
     "Mountain property means wells, septic systems, gravel-road access, and short-term-rental rules. We guide buyers through all of it."),
]

# Geo homes-for-sale pages: (slug, name, county-slug, blurb)
HFS_GEO = [
    ("cleveland", "Cleveland", "bradley-county"),
    ("bradley-county", "Bradley County", "bradley-county"),
    ("charleston", "Charleston", "bradley-county"),
    ("mcdonald", "McDonald", "bradley-county"),
    ("athens", "Athens", "mcminn-county"),
    ("etowah", "Etowah", "mcminn-county"),
    ("benton", "Benton", "polk-county"),
    ("ocoee-copperhill-ducktown", "Ocoee, Copperhill & Ducktown", "polk-county"),
    ("decatur", "Decatur", "meigs-county"),
    ("ten-mile", "Ten Mile", "meigs-county"),
    ("ooltewah", "Ooltewah", "hamilton-county"),
    ("chattanooga", "Chattanooga", "hamilton-county"),
]

LAND_TYPES = [
    ("bradley-county", "Land for Sale in Bradley County",
     "Bradley County land ranges from build-ready lots around Cleveland to large pasture and timber tracts toward Charleston and McDonald. Bender Realty helps buyers and sellers price land the local way — by road frontage, utilities, soil, and location."),
    ("polk-county", "Land for Sale in Polk County",
     "With most of Polk County inside the Cherokee National Forest, private land is scarce and prized — mountain acreage, river frontage on the Hiwassee and Ocoee, and unrestricted tracts in the Copper Basin."),
    ("meigs-county", "Land for Sale in Meigs County",
     "Meigs County offers some of the region's best land value: farms, lake-area acreage near Watts Bar and Chickamauga, and quiet tracts around Decatur and Georgetown."),
    ("mcminn-county", "Land for Sale in McMinn County",
     "McMinn County land runs from I-75 corridor development sites near Athens and Niota to farms and recreational tracts toward Englewood and the Unicoi foothills."),
    ("hunting-land", "Hunting Land for Sale",
     "Southeast Tennessee is serious deer and turkey country. Bender Realty lists hunting tracts with timber, food-plot potential, creek bottoms, and national-forest adjacency across Polk, Meigs, McMinn, and Bradley counties."),
    ("farms", "Farms for Sale",
     "Working farms and hobby farms are a way of life here — cattle pasture, hay ground, poultry operations, and equestrian setups. We help farm buyers evaluate soils, fencing, water, and greenbelt status."),
    ("lakefront-lots", "Lakefront Lots for Sale",
     "Buildable waterfront on Chickamauga and Watts Bar lakes still exists — if you know where to look. We track dockable lots, TVA shoreline classifications, and lake-access communities across the region."),
]

BUY_PAGES = [
    ("prepare-your-finances", "Prepare Your Finances", "How to Prepare Your Finances to Buy a Home in Cleveland TN",
     ["Buying a home starts long before the first showing. Getting your finances in order — credit, savings, and pre-approval — determines what you can buy and how strong your offer will be in the Cleveland TN market.",
      "Start with your credit report: check for errors, pay down revolving balances, and avoid new debt in the months before you apply. Most lenders look for stable employment history and a debt-to-income ratio under about 43%.",
      "Next, get pre-approved — not just pre-qualified — with a lender. In a competitive market like Cleveland and Bradley County, sellers take pre-approved buyers seriously. A Bender Realty agent can connect you with trusted local lenders who know this market and close on time.",
      "Finally, budget beyond the down payment: closing costs typically run 2–5% of the purchase price, and you'll want reserves for inspections, moving, and immediate repairs."],
     [("How much do I need for a down payment in Tennessee?", "Many buyers put down far less than 20%. Conventional loans allow as little as 3% down, FHA loans 3.5%, and USDA loans — available in much of rural Bradley, Polk, McMinn, and Meigs counties — offer 0% down for qualified buyers."),
      ("What credit score do I need to buy a home?", "Most conventional loans look for a score of 620 or higher, while FHA loans can go lower. Higher scores earn better interest rates, so it pays to improve your credit before applying."),
      ("Should I get pre-approved before looking at homes?", "Yes. Pre-approval tells you exactly what you can afford and shows sellers you're a serious buyer — which matters when a well-priced Cleveland home draws multiple offers.")]),
    ("making-a-strong-offer", "Making a Strong Offer", "How to Make a Strong Offer on a Home in Cleveland TN",
     ["When the right home hits the market in Cleveland or Bradley County, well-priced listings can move fast. A strong offer is about more than price — terms, timing, and presentation all matter.",
      "Your Bender Realty agent will run a comparative market analysis so you offer from evidence, not emotion. We look at recent nearby sales, condition, and days on market to find the number that wins without overpaying.",
      "Beyond price, sellers weigh earnest money, financing strength, inspection timelines, and closing dates. Sometimes matching the seller's preferred closing date beats a higher price from a slower buyer.",
      "We prepare every offer to present you as the buyer the seller wants to work with — pre-approved, organized, and ready to close."],
     [("How much earnest money is typical in Cleveland TN?", "Earnest money in the Cleveland area commonly runs about 1% of the purchase price, though it varies by price point and competition. It's credited back to you at closing."),
      ("Can I make an offer contingent on selling my current home?", "Yes, home-sale contingencies are common — but they weaken an offer in competitive situations. Your agent can help you structure timing, or explore buying first with bridge options."),
      ("Should I waive the inspection to win a house?", "We rarely recommend waiving inspections. There are safer ways to strengthen an offer — shorter inspection windows, larger earnest money, or flexible closing dates.")]),
    ("home-closing-process", "The Closing Process", "The Home Closing Process in Tennessee, Step by Step",
     ["From accepted offer to keys in hand usually takes 30–45 days in Tennessee. Knowing what happens at each step keeps the process smooth and surprise-free.",
      "After contract acceptance, you'll deposit earnest money, schedule inspections, and finalize your loan application. Your lender orders an appraisal while a title company searches the property's title and prepares closing documents.",
      "The inspection period is your window to identify issues and negotiate repairs or credits. Your Bender Realty agent handles these negotiations and keeps every deadline on track.",
      "At closing, you'll review and sign the final documents, funds are disbursed, and the deed is recorded. Tennessee is an attorney/title-company closing state, and we coordinate with all parties so closing day is a celebration, not a scramble."],
     [("How long does closing take in Tennessee?", "Most financed purchases close in 30–45 days from contract. Cash purchases can close in as little as one to two weeks."),
      ("What are closing costs for buyers in Tennessee?", "Buyer closing costs typically run 2–5% of the purchase price, covering lender fees, title insurance, taxes, and prepaid escrow items. Your lender provides an itemized estimate up front."),
      ("Do I need a final walk-through?", "Yes — we always schedule a walk-through within 24 hours of closing to confirm the home's condition and that any negotiated repairs were completed.")]),
    ("first-time-homebuyers-cleveland-tn", "First-Time Homebuyers", "First-Time Homebuyer Guide for Cleveland TN",
     ["Buying your first home in Cleveland TN is one of the best financial moves you can make — median prices here remain well below the national average, and rents keep climbing. But the process can feel overwhelming without a guide.",
      "Bender Realty has walked first-time buyers through this market since 1969. We explain each step in plain language: budgeting, loan options, house hunting, offers, inspections, and closing.",
      "Tennessee offers real help for first-time buyers, including THDA Great Choice loans with down-payment assistance, plus FHA and USDA programs that fit the Cleveland area well.",
      "Our agents help you separate must-haves from nice-to-haves, target the right neighborhoods and school zones, and avoid the mistakes first-time buyers most often make."],
     [("What programs help first-time buyers in Tennessee?", "THDA's Great Choice Home Loan offers competitive rates and up to $6,000 in down-payment assistance for qualified Tennessee buyers. FHA, VA, and USDA loans are also popular in the Cleveland area."),
      ("How much house can I afford in Cleveland TN?", "A common guideline is to keep your total housing payment under about 28% of gross monthly income. With Cleveland's home prices, many renters find a mortgage payment comparable to their current rent."),
      ("What neighborhoods are good for first-time buyers in Cleveland?", "It depends on your budget and commute, but first-time buyers often look at established neighborhoods in central and south Cleveland, with newer starter communities toward Hopewell and North Cleveland. A Bender agent can match neighborhoods to your price range.")]),
    ("relocating-to-cleveland-tn", "Relocating to Cleveland TN", "Relocating to Cleveland TN — A Local's Guide",
     ["Thinking about moving to Cleveland, Tennessee? You're not alone — Bradley County is one of the state's steady growth stories, drawing families and remote workers with low costs, no state income tax, and a location 30 minutes from Chattanooga and 2.5 hours from Atlanta or Nashville.",
      "Cleveland offers a rare combination: a real downtown, Lee University's campus energy, strong industry (Whirlpool, Wacker, Amazon and more), and the Ocoee River and Cherokee National Forest at your doorstep.",
      "Housing costs remain a major draw. Your budget goes further here than in the Chattanooga metro, whether you're after a historic in-town home, new construction, or acreage outside the city.",
      "Bender Realty has helped families relocate here since 1969. We provide neighborhood tours, school information, commute guidance, and honest advice about where your lifestyle fits best."],
     [("Is Cleveland TN a good place to live?", "Cleveland combines small-city affordability with big-region amenities: strong schools, Lee University, a growing downtown, major employers, and world-class outdoor recreation within 30 minutes. Tennessee also has no state income tax."),
      ("What is the cost of living in Cleveland TN?", "Cleveland's overall cost of living sits below the national average, with housing the biggest saving — median home prices run well under the U.S. median."),
      ("How far is Cleveland TN from Chattanooga?", "About 30 miles — roughly a 30–40 minute drive via I-75, making Chattanooga's airport, employers, and entertainment an easy commute.")]),
    ("mortgage-calculators", "Mortgage Calculators", "Mortgage Calculators — Estimate Your Payment",
     ["Use these tools to estimate a monthly payment, compare loan terms, and understand what different down payments mean for your budget.",
      "A typical monthly payment includes principal, interest, property taxes, and homeowners insurance (PITI) — plus PMI if your down payment is under 20%, and HOA dues where applicable.",
      "Bradley County's property tax rates are modest compared to national norms, which helps monthly affordability across the Cleveland area.",
      "For exact numbers and today's rates, connect with a local lender — a Bender Realty agent can recommend lenders who consistently perform for our clients."],
     [("What's included in a monthly mortgage payment?", "Principal, interest, property taxes, and homeowners insurance — often abbreviated PITI. Loans with less than 20% down usually add private mortgage insurance (PMI)."),
      ("How do property taxes work in Bradley County?", "Property taxes are based on the county's assessment ratio and tax rate, and are typically collected monthly through your mortgage escrow. Rates in Bradley County are moderate compared to national averages.")]),
]

SELL_PAGES = [
    ("home-valuation", "Home Valuation", "What's My Home Worth? Free Home Valuation in Cleveland TN",
     ["Your home's value changes with the market — and in Southeast Tennessee, the market has moved significantly in recent years. Get a professional opinion of value from the team that's priced Cleveland-area homes since 1969.",
      "Automated estimates you see online are built from broad data and often miss what matters locally: your street, your updates, your lot, and what comparable homes actually sold for last month.",
      "A Bender Realty valuation combines recent comparable sales, current competition, and 55 years of local pricing experience — free, and with no obligation.",
      "Fill out the form below or call us and we'll prepare your personalized market analysis."],
     [("How accurate are online home value estimates?", "Automated estimates can miss by 5–10% or more because they can't see your home's condition, updates, or micro-location. A local comparative market analysis is far more precise."),
      ("Is a home valuation really free?", "Yes. Bender Realty provides complimentary market analyses with no obligation — it's how we begin every seller conversation."),
      ("How long does a home valuation take?", "We can usually deliver a detailed comparative market analysis within a business day or two of seeing your home.")]),
    ("request-a-home-evaluation", "Request a Home Evaluation", "Request a Professional Home Evaluation from Bender Realty",
     ["Ready for a precise, professional evaluation of your property? Tell us about your home and a Bender Realty agent will prepare a full comparative market analysis (CMA).",
      "Your CMA includes recent comparable sales, active competition, market trends in your neighborhood, and a recommended pricing strategy for today's conditions.",
      "There's no cost and no obligation — just an honest, local read on what your property should bring."],
     [("What's the difference between a CMA and an appraisal?", "A CMA is a market analysis prepared by a real estate professional to guide pricing; an appraisal is a formal valuation by a licensed appraiser, typically ordered by a lender during a sale."),
      ("Do I need to prepare my home before the evaluation?", "No — we evaluate homes as they are. If improvements would meaningfully raise your sale price, we'll tell you which ones are worth it and which aren't.")]),
    ("prepare-your-home-for-sale", "Prepare Your Home for Sale", "How to Prepare Your Home for Sale in Cleveland TN",
     ["First impressions set the price. Homes that show well in Cleveland's market sell faster and closer to asking — and preparation doesn't have to mean expensive renovations.",
      "Start with the free stuff: declutter every room, deep clean, brighten (open blinds, raise wattage), and tidy the yard. Buyers decide in the first sixty seconds.",
      "Small-dollar fixes with outsized returns: fresh neutral paint, updated cabinet hardware, mulch and seasonal color at the entry, and repairing the little things buyers notice on inspection anyway.",
      "Your Bender Realty agent will walk your home before listing and give you a specific, prioritized punch list — what to do, what to skip, and what professional staging or photography will do for your particular property."],
     [("What improvements add the most value before selling?", "Paint, lighting, curb appeal, and minor kitchen/bath refreshes consistently return more than their cost. Full remodels rarely pay back at sale time — ask before you spend."),
      ("Should I stage my home?", "Occupied homes usually need editing more than staging — decluttering and furniture arrangement. For vacant homes, targeted staging of key rooms often pays for itself."),
      ("Do I need professional photos?", "Yes — nearly all buyers start online, and professional photography measurably increases showings. It's part of Bender Realty's standard marketing for every listing.")]),
    ("marketing-plan", "Our Marketing Plan", "How Bender Realty Markets Your Home",
     ["Selling well is a marketing job, and we treat it like one. Every Bender Realty listing gets a complete plan built to reach the largest pool of qualified buyers.",
      "Your home is listed on the River Counties MLS and syndicated to the major portals buyers actually use — Zillow, Realtor.com, and hundreds of brokerage sites — with professional photography and compelling copy.",
      "Beyond the portals: targeted social media exposure, our buyer database built over 55 years in this market, agent-to-agent networking across Southeast Tennessee, open houses where they make sense, and yard presence that still matters in a market like ours.",
      "You'll get regular reporting on showings, feedback, and market response — and honest advice if the market tells us to adjust."],
     [("Where will my home be advertised?", "On the River Counties MLS, all major national real estate portals, Bender Realty's website and social channels, and directly to our network of local agents and active buyers."),
      ("How important are listing photos?", "Critically important — listing photos are your home's first showing. We use professional photography on every listing."),
      ("Will you hold open houses?", "When they serve the strategy, yes. Open houses work well for certain price points and locations; your agent will recommend what fits your home.")]),
    ("review-offers-negotiate", "Reviewing Offers & Negotiating", "How to Review Offers and Negotiate the Best Terms",
     ["The highest offer isn't always the best offer. Financing strength, contingencies, timelines, and earnest money all determine whether an offer actually closes — and at what real net to you.",
      "Your Bender Realty agent breaks down every offer side by side: price, loan type and lender reputation, inspection and appraisal contingencies, closing date, and requested concessions.",
      "In multiple-offer situations we run a structured process that keeps every buyer at the table while protecting your leverage. In slower moments, we know how to negotiate without losing the buyer.",
      "After inspection, the second negotiation begins — repair requests. We help you respond in a way that keeps the deal together without giving away more than the market requires."],
     [("Should I always take the highest offer?", "Not necessarily. A slightly lower cash or strongly pre-approved offer with clean contingencies often nets more than a higher offer that falls apart in financing."),
      ("What is an escalation clause?", "A clause where a buyer offers to beat competing offers by a set increment up to a cap. They're common in multiple-offer situations, and your agent will help you evaluate them."),
      ("Can I counter more than one offer at once?", "Tennessee allows multiple counteroffers with proper disclosure and drafting. Your agent manages this carefully to avoid accidentally selling the house twice.")]),
    ("seller-closing-process", "Seller Closing Process", "The Seller's Closing Process in Tennessee",
     ["Once you've accepted an offer, the clock starts: inspections, appraisal, title work, and final documents, typically over 30–45 days. Here's what to expect as a Tennessee seller.",
      "During the inspection period, the buyer may request repairs or credits — your agent negotiates these. Then the buyer's lender orders an appraisal; if it comes in low, there's another negotiation, and we handle that too.",
      "Meanwhile, the title company searches your title, resolves any liens or issues, and prepares the deed and settlement statement. You'll see your estimated net proceeds before closing day.",
      "At closing you sign the deed and settlement documents, hand over the keys, and the proceeds are wired to you — usually the same day."],
     [("What do sellers pay at closing in Tennessee?", "Typical seller costs include the agreed commission, title and closing fees, prorated property taxes, and any negotiated concessions. Your agent provides a net-proceeds estimate before you list and before you accept any offer."),
      ("Do I have to attend closing in person?", "Not always — Tennessee closings can often be handled with pre-signed documents or a mobile notary if you've already moved."),
      ("When do I have to move out?", "Possession transfers at closing unless your contract says otherwise. If you need time after closing, we can negotiate a short possession-after-closing agreement up front.")]),
]

SELL_GEO = [
    ("cleveland", "Sell Your Home in Cleveland TN",
     "Cleveland's steady growth keeps buyer demand healthy across every price range — but pricing and preparation still separate top-dollar sales from listings that sit. Bender Realty has priced and sold Cleveland homes since 1969, and no firm knows these neighborhoods better."),
    ("athens", "Sell Your Home in Athens TN",
     "Athens draws steady buyer interest from commuters along I-75, Tennessee Wesleyan families, and relocators seeking small-town value. Bender Realty markets Athens listings to buyers across Southeast Tennessee, not just in-town."),
    ("decatur", "Sell Your Home in Decatur TN",
     "Meigs County properties — especially anything near Watts Bar or Chickamauga Lake — attract buyers from Chattanooga, Knoxville, and beyond. We make sure your Decatur-area listing reaches them."),
]

BLOG_CATEGORIES = [
    ("buying", "Buying", "Advice for home buyers across Cleveland, Bradley County, and Southeast Tennessee — financing, offers, inspections, and finding the right neighborhood."),
    ("selling", "Selling", "Seller strategy for the Southeast Tennessee market — pricing, preparation, marketing, and negotiating your best outcome."),
    ("market-stats", "Market Stats", "Monthly Cleveland TN and Southeast Tennessee market reports — prices, inventory, days on market, and what it means for you."),
    ("community-news", "Community News", "What's happening across Cleveland, Bradley County, and our surrounding communities — openings, events, and local growth."),
    ("property-management", "Property Management", "Tips for rental owners and tenants — leasing, maintenance, and getting the most from investment property."),
    ("lake-life", "Lake Life", "Living on and around Chickamauga Lake, Watts Bar Lake, and the Ocoee — waterfront buying tips and lake community news."),
]

BLOG_POSTS = [
    ("cleveland-tn-market-report", "Cleveland TN Real Estate Market Report", "market-stats",
     "A look at current conditions in the Cleveland TN and Bradley County housing market — pricing trends, inventory levels, and what buyers and sellers should expect this season.",
     ["The Cleveland TN market continues to reflect the broader Southeast Tennessee story: steady demand, limited inventory in the most requested neighborhoods and school zones, and prices that — while well above pre-2020 levels — remain attractive compared to the Chattanooga metro and the national median.",
      "For sellers, well-prepared and correctly priced homes are still commanding strong attention, particularly in North Cleveland, Hopewell, and the established neighborhoods near downtown. Overpriced listings, by contrast, are sitting longer than they did a year ago — the market rewards accuracy.",
      "For buyers, more balance means more opportunity: inspection contingencies are back, and negotiating room exists on homes with longer days-on-market. Financing costs remain the biggest budget factor, so a conversation with a local lender is the right first step.",
      "Bender Realty publishes market updates regularly. For a neighborhood-specific read on your home's value, request a free evaluation — data beats guesswork every time."]),
    ("moving-to-cleveland-tn-guide", "Moving to Cleveland TN: What to Know Before You Relocate", "community-news",
     "Thinking about relocating to Cleveland, Tennessee? Here's a local's overview of neighborhoods, schools, commutes, and cost of living.",
     ["Cleveland keeps landing on relocation shortlists for good reasons: no state income tax, housing costs below the national average, a real downtown with local restaurants, and world-class outdoor recreation from the Ocoee River to Chickamauga Lake — all within 30 minutes of Chattanooga.",
      "Neighborhood-wise, newcomers tend to compare North Cleveland's newer subdivisions and shopping convenience with the character of the historic districts near downtown, and the space of Hopewell, Georgetown, or McDonald just outside town.",
      "Families weigh Cleveland City Schools against Bradley County Schools — both have strong options, and school zoning often drives the neighborhood decision. Lee University and Cleveland State add college-town energy and steady rental demand.",
      "Our advice after 55 years here: visit on a weekday, drive your actual commute, and let a local agent tour you through three or four different areas before you decide. When you're ready, Bender Realty's relocation guide and our agents are at your service."]),
    ("chickamauga-vs-watts-bar-lakefront", "Chickamauga vs. Watts Bar: Choosing Your Tennessee Lake", "lake-life",
     "Both lakes offer big water and beautiful shoreline — but they suit different lifestyles and budgets. Here's how Southeast Tennessee's two big lakes compare for waterfront buyers.",
     ["Chickamauga Lake stretches from the Chickamauga Dam at Chattanooga up past Harrison, Soddy-Daisy, and Sale Creek — it's the more developed lake, with marinas, restaurants, and quick access to the city. Waterfront here commands a premium, especially dockable property in the Harrison and Soddy-Daisy areas.",
      "Watts Bar Lake, upstream to the north, runs through Meigs, Rhea, and Roane counties with a quieter, more rural shoreline. Areas like Ten Mile and Euchee offer some of the most affordable big-water frontage in East Tennessee — often tens of thousands less than comparable Chickamauga property.",
      "Key questions for any Tennessee lakefront purchase: Is the shoreline dockable under TVA guidelines? What's the water depth at the bank in winter drawdown? Is the property in a flood zone, and what does insurance cost?",
      "Bender Realty tracks waterfront inventory on both lakes. If you're weighing lake life, we'll help you compare real options side by side — start with our lakefront homes page or give us a call."]),
]

AGENTS_NOTE = "Our full agent directory — photos, bios, and direct contact for every Bender Realty agent — will be connected here from our agent management system. In the meantime, call the office and we'll match you with the right agent for your needs."
